<?php

namespace WhiteOctober\QueueBundle\Repository;

use Doctrine\ORM\EntityRepository;

use WhiteOctober\QueueBundle\Entity\QueueEntry;

/**
 * QueueEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueEntryRepository extends EntityRepository
{
    public function getOutstandingEntries($limit = 0, $entryType = null)
    {
        $qry = $this->
            createQueryBuilder("c")->
            where("c.status = :status")->
            orderBy("c.priority", "ASC")->
            addOrderBy("c.createdAt", "ASC")
        ;
        $qry->setParameter("status", QueueEntry::NOT_STARTED);
        if ($limit > 0) {
            $qry->setMaxResults($limit);
        }
        if ($entryType) {
            $qry->andWhere("c.type = :entry_type");
            $qry->setParameter("entry_type", $entryType);
        }

        return $qry->getQuery()->execute();
    }

    /**
     * Deletes entries by type and data
     *
     * @param $type
     * @param $data
     */
    public function removeByTypeAndData($type, $data)
    {
        $qry = $this->
            createQueryBuilder("c")->
            delete()->
            where("c.type = :type")->
            andWhere("c.data = :data");
        $qry->setParameter("type", $type);
        $qry->setParameter("data", $data);
        $qry->getQuery()->execute();
    }
}
